version: "3"
services:
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/innovation-group-test
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php82-service
            - mysql8-service
    php82-service:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php82-container
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/innovation-group-test
    mysql8-service:
        container_name: mysql8-container
        build:
            context: .
            dockerfile: ./docker/mysql/Dockerfile
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/lib:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
